### ISSUE TITLE
Change RibbonGroupSkin's Dependency on LabeledText

### ISSUE THREAD

**Issue by akorynta** [dukke/FXRibbon#13]
This is currently standing in the way of being compliant with current versions of Java.

**Comment by dukke** [comment]
You're absolutely right. Unfortunately haven't had time for fxribbon. 

It is now fixed.

The code with this fixed has been pushed to the repo. I'll make a new release till the end of the weekend.

I've also created two sub-projects, one for the library code and one for the samples. I've also clean up some other things.
