### ISSUE TITLE
Provide license information

### ISSUE THREAD

**Issue by koppor** [dukke/FXRibbon#3]
It would be helpful if you put a license information on your project. http://choosealicense.com/ might be helpful. That page also lists reasons why no license might be problematic: http://choosealicense.com/no-license/

**Comment by RAnders00** [comment]
:+1:

**Comment by Pitority** [comment]
Hey dukke, please follow the links kopper provided. It only takes you 5 minutes. But as long as you dont provide a license, no one is allowed to use your code. Which is really a pity since you obviously put decent effort into it.

**Comment by dukke** [comment]
Done. 

Sorry for taking a long time to do this.

**Comment by koppor** [comment]
Thank you for adding https://github.com/dukke/FXRibbon/blob/master/LICENSE.txt
