### ISSUE TITLE
how to use this software

### ISSUE THREAD

**Issue by Biggo6** [dukke/FXRibbon#4]
hello!

please can you  tell us how to use this with examples please

**Comment by klolo** [comment]
Do you have plan to put this library to maven repository?

**Comment by Biggo6** [comment]
@klolo yeas

**Comment by dukke** [comment]
OK, I'll do that.

In the future please file a new issue, thanks.

**Comment by dukke** [comment]
@Biggo6 Are the new documentation page along with the test examples on the test folder good for this issue you've raised?

**Comment by Biggo6** [comment]
@dukke new doc looks amazing

**Comment by dukke** [comment]
@Biggo6 Thanks, closing this issue then..
